name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  style-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.11

      - uses: actions/setup-node@v5
        with:
          node-version: |
            20

      - name: Add .local path
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
          echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Install Base Dependencies
        run: |
          sudo apt-get install python3-venv pipx
          pipx install hatch

      - name: Run style checks
        run: |
          hatch run style --exit-non-zero-on-fix
